"""
Рендер docs/REPORT.md в одностраничный PDF через цепочку:
  markdown.markdown(...)  →  REPORT.html  →  msedge --headless --print-to-pdf  →  REPORT.pdf

Зачем такой путь:
- pandoc + LaTeX (xelatex) — самый «академический» рендер, но требует LaTeX-дистрибутива (~3 ГБ).
- weasyprint / wkhtmltopdf — отдельная установка, нестабильны на Windows.
- Edge / Chrome headless — есть на каждой Windows-машине из коробки, поддерживает CSS print, кириллицу,
  embedding изображений по относительным путям из file:// URL. Один вызов, без зависимостей.

Запуск:
    python scripts/render_report_pdf.py

Результат: docs/REPORT.html + docs/REPORT.pdf
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import markdown

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "docs" / "REPORT.md"
HTML = ROOT / "docs" / "REPORT.html"
PDF = ROOT / "docs" / "REPORT.pdf"

EDGE_CANDIDATES = [
    Path(r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"),
    Path(r"C:\Program Files\Microsoft\Edge\Application\msedge.exe"),
    Path(r"C:\Program Files\Google\Chrome\Application\chrome.exe"),
    Path(r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"),
]


# ---------------------------------------------------------------------------
# 1. Markdown → HTML
# ---------------------------------------------------------------------------

CSS = r"""
@page {
  size: A4;
  margin: 1.8cm 2cm 1.8cm 2cm;
}

body {
  font-family: "Times New Roman", "Liberation Serif", serif;
  font-size: 11pt;
  line-height: 1.45;
  color: #1a1a1a;
  max-width: 18cm;
  margin: 0 auto;
  padding: 0 0.5cm;
}

h1 {
  font-size: 18pt;
  border-bottom: 2px solid #333;
  padding-bottom: 0.2em;
  margin-top: 0;
  page-break-before: always;
  page-break-after: avoid;
}
h1:first-of-type { page-break-before: avoid; }
h2 {
  font-size: 14pt;
  border-bottom: 1px solid #ccc;
  padding-bottom: 0.15em;
  margin-top: 1.6em;
  page-break-after: avoid;
}
h3 {
  font-size: 12pt;
  margin-top: 1.3em;
  page-break-after: avoid;
}
h4 { font-size: 11pt; font-weight: bold; margin-top: 1em; }

p { margin: 0.5em 0; text-align: justify; }

a { color: #0a58ca; text-decoration: none; word-break: break-all; }
a:hover { text-decoration: underline; }

strong { font-weight: bold; }
em { font-style: italic; }

code {
  font-family: Consolas, "Liberation Mono", monospace;
  font-size: 9.5pt;
  background: #f3f3f3;
  padding: 0.05em 0.3em;
  border-radius: 3px;
}

pre {
  font-family: Consolas, "Liberation Mono", monospace;
  font-size: 9pt;
  background: #f7f7f7;
  border: 1px solid #ddd;
  border-radius: 4px;
  padding: 0.7em 1em;
  overflow: auto;
  line-height: 1.35;
  page-break-inside: avoid;
}
pre code { background: transparent; padding: 0; font-size: inherit; }

blockquote {
  margin: 1em 0;
  border-left: 4px solid #aaa;
  padding: 0.3em 1em;
  color: #555;
  background: #fafafa;
}

table {
  border-collapse: collapse;
  margin: 1em 0;
  font-size: 10pt;
  width: 100%;
  page-break-inside: avoid;
}
th, td {
  border: 1px solid #888;
  padding: 0.35em 0.6em;
  text-align: left;
  vertical-align: top;
}
th { background: #efefef; font-weight: bold; }

img {
  max-width: 100%;
  height: auto;
  display: block;
  margin: 0.8em auto;
  page-break-inside: avoid;
}

ul, ol { margin: 0.5em 0; padding-left: 1.6em; }
li { margin: 0.2em 0; }

hr { border: none; border-top: 1px solid #ccc; margin: 1.5em 0; }

/* Title block */
.title-block {
  text-align: center;
  margin: 1cm 0 2cm 0;
  page-break-after: always;
}
.title-block .title { font-size: 20pt; font-weight: bold; margin-bottom: 0.5em; }
.title-block .subtitle { font-size: 14pt; color: #555; margin-bottom: 2em; }
.title-block .author { font-size: 12pt; margin-bottom: 0.3em; }
.title-block .date { font-size: 11pt; color: #777; }

/* Table of Contents (auto-generated by toc extension) */
.toc {
  background: #f8f8f8;
  border: 1px solid #ddd;
  padding: 0.8em 1.2em;
  margin: 1em 0 2em 0;
  page-break-after: always;
}
.toc > ul { padding-left: 1em; }
.toc ul { list-style: none; }
.toc a { color: #1a1a1a; }
.toc-title { font-size: 14pt; font-weight: bold; margin-bottom: 0.5em; }
"""


def md_to_html(md_text: str) -> tuple[str, dict]:
    # Парсим YAML-frontmatter в meta для титульного блока
    meta: dict[str, str] = {}
    m = re.match(r"^---\n(.*?)\n---\n", md_text, flags=re.DOTALL)
    if m:
        for line in m.group(1).splitlines():
            if ":" in line:
                k, _, v = line.partition(":")
                meta[k.strip()] = v.strip().strip('"').strip("'")
        md_text = md_text[m.end():]

    # Заменяем pandoc-LaTeX директивы на HTML-эквиваленты
    md_text = md_text.replace(
        r"\newpage", '<div style="page-break-after: always;"></div>'
    )
    md_text = md_text.replace(r"\tableofcontents", "[TOC]")

    md = markdown.Markdown(
        extensions=[
            "extra",       # tables, fenced_code, footnotes, attr_list, def_list, etc.
            "toc",         # auto-TOC при [TOC]
            "sane_lists",
            "codehilite",  # подсветка кода через pygments
        ],
        extension_configs={
            "toc": {"title": "Содержание", "permalink": False},
            "codehilite": {"guess_lang": False, "use_pygments": True},
        },
    )

    body = md.convert(md_text)
    return body, meta


def build_html(body: str, meta: dict) -> str:
    title = meta.get("title", "Отчёт")
    subtitle = meta.get("subtitle", "")
    author = meta.get("author", "")
    date = meta.get("date", "")

    title_block = f"""
<div class="title-block">
  <div class="title">{title}</div>
  <div class="subtitle">{subtitle}</div>
  <div class="author">{author}</div>
  <div class="date">{date}</div>
</div>
"""

    return f"""<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <title>{title}</title>
  <style>{CSS}</style>
</head>
<body>
{title_block}
{body}
</body>
</html>
"""


# ---------------------------------------------------------------------------
# 2. HTML → PDF via Edge headless
# ---------------------------------------------------------------------------


def find_edge() -> Path:
    for c in EDGE_CANDIDATES:
        if c.exists():
            return c
    raise RuntimeError(
        "Не найден ни Edge, ни Chrome. Установите Edge или укажите путь вручную."
    )


def html_to_pdf(html_path: Path, pdf_path: Path, browser: Path) -> None:
    """
    Edge --headless=new --print-to-pdf — самый надёжный способ HTML→PDF без сторонних либ.
    `--no-pdf-header-footer` убирает дату и URL Edge'а из футера/хедера PDF.
    """
    url = html_path.resolve().as_uri()
    cmd = [
        str(browser),
        "--headless=new",
        "--disable-gpu",
        "--no-pdf-header-footer",
        f"--print-to-pdf={pdf_path.resolve()}",
        url,
    ]
    print(f"  cmd: {' '.join(cmd[:3])} ... {pdf_path.name}")
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    if result.returncode != 0:
        print(result.stdout)
        print(result.stderr, file=sys.stderr)
        raise RuntimeError(f"Edge headless failed (rc={result.returncode})")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def main() -> int:
    if not SRC.exists():
        print(f"NOT FOUND: {SRC}", file=sys.stderr)
        return 1

    print(f"reading: {SRC}")
    md_text = SRC.read_text(encoding="utf-8")

    print("rendering markdown -> html ...")
    body, meta = md_to_html(md_text)
    html = build_html(body, meta)
    HTML.write_text(html, encoding="utf-8")
    print(f"  saved: {HTML} ({len(html):,} chars)")

    print("rendering html -> pdf via Edge headless ...")
    browser = find_edge()
    print(f"  using browser: {browser}")
    html_to_pdf(HTML, PDF, browser)
    if not PDF.exists():
        print("PDF was not produced", file=sys.stderr)
        return 1
    print(f"  saved: {PDF} ({PDF.stat().st_size:,} bytes)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
